### PR TITLE
Enhance config options

### LINKED ISSUE #327: Ring suppression
Is there an option to enable the Ring suppression as it is described here for nuki ng (https://github.com/kvj/hass_nuki_ng/issues/76)?

Best wishes

### PR DESCRIPTION
**Pull request by iranl**
- [x] Add every config and advanced config option to MQTT (JSON)
- [x] Separate config state from config actions in MQTT (same as lockstate/action and keypad codes/action)
- [x] ACL for every separate config option
- [x] Make some config/advanced config options more human readable
- [x] Allow modifying every config and advanced config option through MQTT
- [x] Modify existing config Home Assistant auto discovery topics
- [x] Add new config Home Assistant auto discovery topics
- [x] Update README
- [x] Enable/disable all button for ACL options in WebCfg
- [x] Final minor adjustments and testing
- [x] Update Arduino Core to 2.0.15 (won't build otherwise using Actions/Dockerfile)

NOTE: Breaking change as the existing configuration MQTT topics can not be used for changing settings if this is merged.

Closes #327

### CODE REVIEW

**Comment by iranl** [comment]
@technyon This PR needs the most recent changes in I-Connect/NukiBleEsp32. Can you sync nuki_ble with upstream?

**Comment by technyon** [comment]
Hi,

Sorry I didn't see your comment. nuki_ble is now updated.

One more thing: Since there are breaking changes in this PR, could we have a discussion on github? Not that I'm against it, I'd just like to hear some more opinions.

**Comment by iranl** [comment]
Binary available for testing from the Github Actions artifacts: https://github.com/technyon/nuki_hub/actions/runs/8644273771/artifacts/1404437356

**Comment by iranl** [comment]
Binary available for testing from the Github Actions artifacts: https://github.com/technyon/nuki_hub/actions/runs/8644273771/artifacts/1404437356

**Comment by technyon** [comment]
@iranl Before merging, could you post a binary for testing on discord?

**Comment by iranl** [comment]
As requested, also posted on Discord.

[nuki_hub-8.34-pre-2.zip](https://github.com/technyon/nuki_hub/files/14958890/nuki_hub-8.34-pre-2.zip)

**Comment by iranl** [comment]
Converted to draft because of issues reported in #327

**Comment by iranl** [comment]
Added fixes for stability issues with the combination of an opener and lock.

[nuki_hub-8.34-pre-3.zip](https://github.com/technyon/nuki_hub/files/14982292/nuki_hub-8.34-pre-3.zip)

**Comment by technyon** [comment]
Hi. There are a lot of changes in this PR, and some potential stability issues have been reported. We should to some thorough testing before merging. Is the -pre-3 binary up-to-date?

**Comment by iranl** [comment]
Pre-3 is not up to date.

Do you want to include #340 in 8.34?
#340 is a pretty minor addition which is basically a copy of the JSON keypad control.

If so I will build Pre-4 after merging #340 from master + this PR.
If not I will build Pre-4 from the current state of this PR.

**Comment by technyon** [comment]
Hi,

I've merged your other PRs. Could you update and build an up-to-date binary

**Comment by iranl** [comment]
Binaries for pre-4:

[esp32dev-assets.zip](https://github.com/technyon/nuki_hub/files/15112120/esp32dev-assets.zip)
[esp32-s3-assets.zip](https://github.com/technyon/nuki_hub/files/15112121/esp32-s3-assets.zip)
[esp32solo1-assets.zip](https://github.com/technyon/nuki_hub/files/15112122/esp32solo1-assets.zip)
[esp32-c3-assets.zip](https://github.com/technyon/nuki_hub/files/15112123/esp32-c3-assets.zip)

Will run the ESP32 and ESP32-s3 ones for 24h and post them on Discord if I have no issues.

Please note that the merged binaries for Webflash (nuki_hub_esp32[dev/s3/c3/solo1].bin) can't be used for upgrading.
OTA upgrade still needs to be done using the nuki_hub.bin binary from the asset package for the respective ESP version.

**Comment by iranl** [comment]
@katiuskt: I've pushed an update to the W5500 code to change the pinout for the AtomPOE on the S3 to 5/7/8/39 instead of 19/22/23/33

Can you try [esp32-s3-assets.zip](https://github.com/technyon/nuki_hub/files/15192391/esp32-s3-assets.zip)?
Note: Will still show 8.34-pre4

**Comment by iranl** [comment]
I've taken a goed look at the pinouts and it seems the following pinouts translate to the different models:

| Func         | Atom S3 lite ESP32-S3           | Atom lite ESP32    |
|------------|---------------------------------|---------------------|
| CLK          | 6                                             | 19                          |             
| CS            | 5                                             | 22                          |             
| MISO        | 7                                             | 23                          |             
| MOSI        | 8                                             | 33                          |              

In my first try I  assumed the pinout G5/G6/G7/G8/G38/G39 translated to G19/G21/G22/G23/G25/G33.

Please try [esp32-s3-assets.zip](https://github.com/technyon/nuki_hub/files/15200349/esp32-s3-assets.zip)

You can try debugging using the serial console with a program like hterm

**Comment by iranl** [comment]
Good to hear the Atom POE now works on the S3. 

As for the `maintenance/reset` button I agree, this is also the way I have recently implemented the query buttons.
The choice to expose `maintenance/reset` through a switch was made a while ago and changing it would mean a breaking change for people using this switch in an automation. The pros of changing this behaviour don't outweigh the cons of a breaking change at this time in this case imho.

**Pull request merged**
