### PR TITLE
Add C3, S3 and Solo1 support + Build using PlatformIO

### LINKED ISSUE #199: Installation on Shelly 1 Plus
Hello,

I was wondering if anybody has ever tried to install the Firmware on a Shelly 1 Plus?
I tried today. Flashing it via the Web installer was successful, but it seems that the ESP32 isn't able to boot the firmware.

### LINKED ISSUE #201: M5Stack Atom S3 Lite not working
Hi all,

First of all: Apologies if this issue should be reported somewhere else. If so, please let me know.

I'm quite newbie on this ESP32/IoT stuff but recently received a Nuki Opener and I wanted to integrate it into Home Assistant without Nuki Bridge using your solution.
I read M5Stack Atom Lite was recommended so I bought it... sort of, because the one I bought by mistake (I wasn't aware of differences) was the S3 one (https://docs.m5stack.com/en/core/AtomS3%20Lite) and... I'm struggling trying to install Nuki Hub on it.
I'm not even sure if it is compatible at all :-(

From web installer I get this:
imagen

So I tried using espressif_download_tool. I have no errors

imagen
imagen

But the ESP32 AP doesn't appear so I just wonder if maybe this ESP32S3 is supported.

From 8.24 release notes I can see "Arduino Core for ESP32 to version 2.09" which is the latest and, appartently ESP32S3 are supported (https://docs.espressif.com/projects/arduino-esp32/en/latest/getting_started.html#supported-soc-s) so I guess it should work with nuki_hub and just maybe something should be tweaked at flashing process?

I will really appreciate if confirmation can be provided about this and, if it is not supported I will be glad to provide the information I can to help to test it.

UPDATE: I've been reading and finally tried the esptool method to deploy the files. It seems to confirm ESP32-S3 is not being supported.
Is it planned to support it in the future?

```
C:\Temp\nukihub_8.24>python -m esptool --chip esp32s3 --baud 921600 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size detect 0xe000 boot_app0.bin 0x1000 bootloader_qio_80m.bin 0x10000 nuki_hub.bin 0x8000 nuki_hub.partitions.bin
esptool.py v4.6.2
Found 1 serial ports
Serial port COM4
Connecting...
Chip is ESP32-S3 (revision v0.1)
Features: WiFi, BLE
Crystal is 40MHz
MAC: [redacted]
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Configuring flash size...
Auto-detected Flash size: 8MB
Unexpected chip id in image. Expected 9 but value was 0. Is this image for a different chip model?

A fatal error occurred: bootloader_qio_80m.bin is not an ESP32-S3 image. Use --force to flash anyway.
```

### LINKED ISSUE #259: Compiling Error
I'm trying to compile from source but I always got this error: 

```
Cmake Error at CMakeLists.txt:132 (target_link_arduino_libraries):
   Unknown CMake command "target_link_arduino_libraries".
```
I can't understand how to solve this error, tried to revert back to the original CMakeLists.txt but was the same error

### PR DESCRIPTION
**Pull request by iranl**
-ESP32-S3 build was flashed and tested with success.
-ESP32-C3 and ESP32-Solo1 are untested, but build ok.

Credits for PlatformIO support go to @lucaoliano.
Some changes where required because the bootloader address of the ESP32-S3 and C3 differs from the ESP32.

Closes #199 
Closes #201 
Closes #259 

Leaves CMake support intact.
Artifacts from Github Actions can be used for release zip files and merged binaries in the ZIP files can be used for Webflash.
Could benefit from a release workflow to automate adding binaries to releases/webflash, but I'm no expert in Github Actions.

Also might be an idea to create a Docker build option using PlatformIO and add instructions for building using PlatformIO without Docker.

### CODE REVIEW

**Comment by jolichter** [comment]
Hello, I have tried to flash a new [M5Stamp ESP32 S3](https://docs.m5stack.com/en/core/StampS) (Chip: ESP32-S3FN8) with Nuki Hub 8.33 via Win10.

Could it be that the Nuki Hub doesn't work with it? After flashing and restarting the ESP, I can't find any WiFi, the LED is off and the chip remains cold, so it probably won't start?

The ESP32-S3 is found as
`Bus 001 Device 014: ID 303a:1001 Espressif USB JTAG/serial debug unit`
in the Linux terminal.

and my VM with Win10 detects the ESP as:
`Espressif USB JTAG/serial debug unit [0101]`

Windows console shows after flashing:
```
test offset :  4096 0x1000
case ok
test offset :  32768 0x8000
case ok
test offset :  57344 0xe000
case ok
test offset :  65536 0x10000
case ok

Uploading stub...
Running stub...
Stub running...
Changing baud rate to 115200
Changed.
NO XMC flash  detected!
SPI_BOOT_CRYPT_CNT 0
SECURE_BOOT_EN False
Compressed 18560 bytes to 12759...
Compressed 3072 bytes to 129...
Compressed 8192 bytes to 47...
Compressed 1739312 bytes to 1097401...

 is stub and send flash finish
```
WIN10_Screenshot_ESP32-S3_Flash_Nuki-Hub

If I understand correctly, the chip is not yet supported with Nuki Hub 8.33?

**Comment by iranl** [comment]
You need to use a pre release version of 8.34 right now as support will be added in 8.34.

The latest pre release for S3 can be found in PR #332 and is also available through webflash at https://technyon.github.io/nuki_hub/

**Comment by jolichter** [comment]
Fine, that's the way it works :-)

WIN10_Screenshot_ESP32-S3_Flash_Nuki-Hub

PS: But not via webflash and Chrome Browser. Error message:
`Failed to initialize. Try resetting your device or holding the BOOT button while clicking INSTALL`
(btw. this item has no boot button)

Manny Thanks!

**Comment by iranl** [comment]
Good to hear you've got it working.

According to the docs you linked:

`If you want to enter download mode, press and hold the G0 button on StampS3 before turning it on, then release it after powering it on.`

If you follow this procedure webflash should work, although I haven't tested it on my own S3 yet.

Please note that the 8.34 pre release might include bugs related and unrelated to the S3

**Comment by jolichter** [comment]
Yes, of course. I have only tested my ESP32-S3 briefly, as soon as 8.34 is officially released I will test it longer with my Nuki. For the G0 button, I would have to solder a pin on this device, which was not necessary due to the Flash Tool.

Thanks again for your great work!

**Pull request merged**
