### PR TITLE
Switch HTTP server to PsychicHTTP and MQTT client to ESP-MQTT, remove WiFiManager

### PR DESCRIPTION
**Pull request by iranl**
## Description:

Note: Webserial not yet available for PsychicHTTP and thus disabled/removed (temporarily)

Reduces amount of external dependencies.

Deps after this PR:

**External dependencies**
- Pioarduino (Arduino @ 3.0.5): https://github.com/pioarduino/platform-espressif32
- - HTTPClient
- - NetworkClientSecure
- - Update
- - WiFi
- - Preferences
- - Ethernet
- - Networking
- - SPI
- ArduinoJson (@ 7.2.0): https://github.com/bblanchon/ArduinoJson
- PsychicHttp (@ 1.2.1): https://github.com/hoeken/PsychicHttp
- esp-nimble-cpp: https://github.com/h2zero/esp-nimble-cpp

**Dependencies under control of this project**
- NukiBleEsp: https://github.com/I-Connect/NukiBleEsp32

**Not being maintained**
- BleScanner: https://github.com/I-Connect/BleScanner
- CRC16: https://github.com/vinmenn/Crc16

## Checklist:
  - [x] The pull request is done against the latest master branch
  - [x] Only relevant files were touched
  - [x] The code change is tested and works
  - [x] I accept the [CLA](https://github.com/technyon/nuki_hub/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by iranl** [comment]
As discussed earlier I prefer to include this in beta4 for 9.01 as this PR will revert multiple changes that were introduced after 9.0.
Releasing 9.01 without this PR and reverting/removing changes/new functionality (such as webserial) is not preferably imho.

**Comment by technyon** [comment]
Hi. Too late sorry I saw your comment too late.

**Comment by iranl** [comment]
Np. Let's just not wait with 9.02 for two months

**Comment by technyon** [comment]
Don't worry, smaller incremental updates are better even if we remove features. Webserial isn't something many users use anyway.

I this ready to be tested? In that case let's post it on discord.

**Comment by iranl** [comment]
Yes this is ready to be merged and tested further. Basic testing on my development devices has been completed without issue.

**Pull request merged**
