### PR TITLE
Add latest release check

### LINKED ISSUE #189: Feature Request: Adding a link to current Releases in the UI
As a User I'd like to have a link to the current release (or release page) on github, so I can easily check for updates.

icing on the cake would be a check, if there's already a new release higher than the current release with a direct link to it.

### PR DESCRIPTION
**Pull request by iranl**
Closes #189

Checks latest github release on boot and every 24 hours.

TODO
- [x] Switch to using `https://api.github.com/repos/technyon/nuki_hub/releases/latest`
- [x] Checkbox to enable/disable update check (disabled by default) and publication of topics related to update check
- [x] Home assistant update sensor
- [x] Add new HA topics to removeHASSConfig()
- [x] Add a button to WebCfg to download the latest firmware binary
- [x] Add a button to WebCfg to open the latest release notes

### CODE REVIEW

**Comment by technyon** [comment]
Hi,

thanks for looking into this.

Feel free to join us on discord

**Comment by technyon** [comment]
I see you're including a hard-coded certificate, not sure if this is a good idea. Certificates expire, this one in 2031 which is a long time, but we'll have to make sure to keep it updated. Not sure about alternatives though.

**Comment by iranl** [comment]
> I see you're including a hard-coded certificate, not sure if this is a good idea. Certificates expire, this one in 2031 which is a long time, but we'll have to make sure to keep it updated. Not sure about alternatives though.

Would definitely not be ideal for release. 

Maybe should have kept my testing in regard to truly automatic updating out of this PR, immediatly ran into CPU exceptions while testing this code.

I have removed it from the PR and will consider revisting this functionality in the future.

Instead I added two buttons on the `/ota` page of WebCfg (if update checking is enabled). One that will link to the latest release URL and one that is a direct link to the binary from `/webflash` in master. This would for now be the quickest way to update to latest.

This PR should be ready to go now, I've tested it without issue.

**Comment by alexdelprete** [comment]
This is a long-time wanted functionality. :)

In reality I asked if it was possible to OTA flash from GitHub, to avoid the manual upload of the bin.

So basically have the device download from github and flash. Would it be possible?

Thanks a lot @iranl

**Comment by iranl** [comment]
> This is a long-time wanted functionality. :)
> 
> In reality I asked if it was possible to OTA flash from GitHub, to avoid the manual upload of the bin.
> 
> So basically have the device download from github and flash. Would it be possible?
> 
> Thanks a lot @iranl 

Flashing the binary straight from GitHub should be possible, but too complex to make it part of this PR. Will probably revisit when I'm done with open issues I can contribute to.

**Pull request merged**
