### PR TITLE
Add and remove libs and components for Arduino Core 3

### PR DESCRIPTION
**Pull request by iranl**
## Description:

This adds and removes some components and libraries that are needed (or not needed) for Arduino Core 3 and ESP-IDF.
This is a PR in preparation for the PR that moves Nuki Hub to Arduino Core 3.

All added components and libraries are unmodified from their respective sources.
The removed library (NimBLE-Arduino) will be automatically obtained by the Library manager of Platform IO (until the Arduino Core 3 PR is merged)

This PR does not change anything about the current builds but should make reviewing the Arduino Core 3 PR much easier (as this will change that PR from 1200+ changed files to about 100)

**Related issue (if applicable):** None

## Checklist:
  - [x] The pull request is done against the latest master branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works
  - [x] I accept the [CLA](https://github.com/technyon/nuki_hub/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by technyon** [comment]
Let's please postpone deleting NimBLE. I'd like to keep using CLion, and for that I need to be able to be able with cmake. I'll look into using git fetch to pull the library in from CMakeList.txt, so it doesn't have to be checked in, but I'll have to find some time to do so.

**Comment by iranl** [comment]
NimBLE-Arduino is unusable in core 3.
The follow-up PR for core 3 is done and should be merged as soon as possible (after this PR) imho.
So there isn't really a goed reason to fetch NimBLE-Arduino anymore imho.

Core 3 and esp-nimble-cpp also require building arduino as an esp-idf component.
This setup does not seem compatible with CLion because of conflicting cmakelists.
So using CLion will also not be possible anymore as it is incompatible with esp-idf.

I can understand adherence to ones favourite tools, but Clion imho is not a feasible option when considering the different supported devices and required move to esp-idf if we want to move to the latest Core and IDF versions.

I can probably add back NimBLE in a non breaking way, but do not think this is usefull.

**Comment by technyon** [comment]
There seems to be a way:

https://www.jetbrains.com/help/clion/esp-idf.html

I just need some time to get it running. Does it interfere with the current build process to keep those files? We can still pull the library via platformio, and ignore the checked in files I think. Yes, sooner or later we should remove them.

**Comment by iranl** [comment]
It does interfere with the current build process if NimBLE-Arduino is added to the /lib dir.
I have re-added them to the resources dir and updated the cmakelists file to point to the resources dir.

**Pull request merged**
