### PR TITLE
Refactor DTS to follow the PlatformIO standard structure

### PR DESCRIPTION
**Pull request by lucaoliano**
- The source code files have been moved to the `src` folder.
- Third-party libraries have been removed from the `platformio.ini` file. This is because all the third-party libraries are already present in the `lib` folder, making their inclusion in the configuration file unnecessary.

### CODE REVIEW

**Comment by technyon** [comment]
Hi,

I'd wait with merging this until after PR #332 is completed.

**Comment by lucaoliano** [comment]
Alright, that sounds good. I'll keep an eye on my pull request to make sure it stays in sync with any new changes that come up.

**Comment by technyon** [comment]
@lucaoliano Can you update this branch and resolve the merge conflicts? I'd merge when done.

**Comment by lucaoliano** [comment]
Hi,
done.

**Pull request merged**
