### PR TITLE
BLE fixes

### LINKED ISSUE #326: [Feature Request] Add support for ESP32-C6
I have a esp32-c6 board and I am not capable to install on it. Is this board compatible?

### LINKED ISSUE #432: Nuki Lock freezes(goes offline) after a while when connected to Nuki Hub
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
Nuki Lock 4.0 Pro freezes/goes offline after 20-30h being connected to Nuki Hub, stops being available via BT. It happens only when Lock ist connected to Nuki Hub. The Nuki Lock becomes not available even via original app. The only one fix, that works: remove the battery and put it back 
Tried with FW 8.34 and FW 8.35 - No changes.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ x] Read the [Contributing Guide and Policy](https://github.com/technyon/nuki_hub/blob/master/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/technyon/nuki_hub/blob/master/CODE_OF_CONDUCT.md)
- [ x] Searched the problem in [issues](https://github.com/technyon/nuki_hub/issues)
- [ x] Searched the problem in [discussions](https://github.com/technyon/nuki_hub/discussions)
- [x ] Searched the problem in the [docs](https://github.com/technyon/nuki_hub)
- [ ] Searched the problem in the [chat](https://discord.gg/9nPq85bP4p)
- [x ] Device used (e.g., ESP32-S3): M5 Atom S3 Lite
- [ x] Nuki Hub binary firmware version number used: FW 8.34 and FW 8.35
  - [ x] Pre-compiled
  - [ ] Self-compiled
- [ x] Provide the output of http://nukihubIP/info:
```
Lock config ACL (Timezone offset): Disallowed
Lock config ACL (DST mode): Disallowed
Lock config ACL (Fob Action 1): Disallowed
Lock config ACL (Fob Action 2): Disallowed
Lock config ACL (Fob Action 3): Disallowed
Lock config ACL (Single Lock): Allowed
Lock config ACL (Advertising Mode): Disallowed
Lock config ACL (Timezone ID): Disallowed
Lock config ACL (Unlocked Position Offset Degrees): Disallowed
Lock config ACL (Locked Position Offset Degrees): Disallowed
Lock config ACL (Single Locked Position Offset Degrees): Disallowed
Lock config ACL (Unlocked To Locked Transition Offset Degrees): Disallowed
Lock config ACL (Lock n Go timeout): Disallowed
Lock config ACL (Single button press action): Disallowed
Lock config ACL (Double button press action): Disallowed
Lock config ACL (Detached cylinder): Disallowed
Lock config ACL (Battery type): Disallowed
Lock config ACL (Automatic battery type detection): Disallowed
Lock config ACL (Unlatch duration): Disallowed
Lock config ACL (Auto lock timeout): Disallowed
Lock config ACL (Auto unlock disabled): Allowed
Lock config ACL (Nightmode enabled): Disallowed
Lock config ACL (Nightmode start time): Disallowed
Lock config ACL (Nightmode end time): Disallowed
Lock config ACL (Nightmode auto lock enabled): Disallowed
Lock config ACL (Nightmode auto unlock disabled): Disallowed
Lock config ACL (Nightmode immediate lock on start): Disallowed
Lock config ACL (Auto lock enabled): Allowed
Lock config ACL (Immediate auto lock enabled): Disallowed
Lock config ACL (Auto update enabled): Disallowed
Network device: Built-in Wi-Fi
Uptime: 634 minutes
Heap: 141228
Stack watermarks: nw: 7712, nuki: 2328, pd: 96
Restart reason FW: BLEBeaconWatchdog
Restart reason ESP: ESP_RST_SW: Software reset via esp_restart.
```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Pair Nuki Lock 4 Pro to Nuki Hub, wait for 1-2 days

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
Lock continues doesn't go offline after couple days and continues to be available via BT with the original Nuki App.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

### LINKED ISSUE #438: [9.0-beta/master] No valid Opener config received
### PROBLEM DESCRIPTION
After updating to 9.0 build 10086733497.8.1, the ring detect entities (event and binary sensor) are missing.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/technyon/nuki_hub/blob/master/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/technyon/nuki_hub/blob/master/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/technyon/nuki_hub/issues)
- [x] Searched the problem in [discussions](https://github.com/technyon/nuki_hub/discussions)
- [x] Searched the problem in the [docs](https://github.com/technyon/nuki_hub)
- [x] Searched the problem in the [chat](https://discord.gg/9nPq85bP4p)
- [x] Device used (e.g., ESP32-S3): ESP32
- [x] Nuki Hub binary firmware version number used: 10086733497.8.1
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Provide the output of http://nukihubIP/info:
```
Nuki Hub version: 9.00
Nuki Hub build: 10086733497.8.1
Nuki Hub build type: Release
run: true
confVersion: 900
deviceId: 760860867
deviceIdOp: 760860867
nukiId: ***
nukidOp: ***
mqttbroker: x.x.x.x
mqttport: 8883
mqttuser: ***
mqttpass: ***
mqttlog: true
checkupdates: true
websrvena: false
lockena: true
lockpin: 1
mqttpath: nuki
openerena: true
openerpin: 1
openercont: false
mqttoppath: nukiopener
maxkpad: 
opmaxkpad: 
maxtc: 
opmaxtc: 
enabtlprst: false
mqttca: ***
mqttcrt: 
mqttkey: 
hassdiscovery: homeassistant
hassConfigUrl: 
buffsize: 
dhcpena: true
ipaddr: 
ipsub: 
ipgtw: 10.x.x.x
dnssrv: 10.x.x.x
nwhw: 8
nwwififb: true
rssipb: 10
hostname: nukihub
nwbestrssi: true
nettmout: 60
restdisc: true
rstbcn: 30
lockStInterval: 3600
tcPerEntry: false
kpPerEntry: false
configInterval: 3600
batInterval: 3600
kpInterval: 3600
kpCntrlEnabled: true
kpInfoEnabled: false
kpPubCode: false
tcCntrlEnabled: false
tcInfoEnabled: false
cnfInfoEnabled: false
regAsApp: false
regOpnAsApp: false
nrRetry: 3
rtryDelay: 100
crdusr: ***
crdpass: ***
disnonjson: true
pubAuth: false
pubdbg: false
prdtimeout: -1
offHybrid: false
hybridTimer: 600
hybridAct: false
hybridRtry: false
hasmac: false
macb0: 
macb1: 
macb2: 
latest: 8.35
tsksznetw: 
tsksznuki: 
authmaxentry: 
kpmaxentry: 
tcmaxentry: 
updMqtt: false
showSecr: false
MQTT connected: Yes
Lock firmware version: 3.9.5
Lock hardware version: 2.10
Lock paired: Yes
Lock valid PIN set: Yes
Lock has door sensor: No
Lock has keypad: No
Lock ACL (Lock): Allowed
Lock ACL (Unlock): Allowed
Lock ACL (Unlatch): Allowed
Lock ACL (Lock N Go): Allowed
Lock ACL (Lock N Go Unlatch): Allowed
Lock ACL (Full Lock): Allowed
Lock ACL (Fob Action 1): Allowed
Lock ACL (Fob Action 2): Allowed
Lock ACL (Fob Action 3): Allowed
Lock config ACL (Name): Disallowed
Lock config ACL (Latitude): Disallowed
Lock config ACL (Longitude): Disallowed
Lock config ACL (Auto Unlatch): Disallowed
Lock config ACL (Pairing enabled): Allowed
Lock config ACL (Button enabled): Allowed
Lock config ACL (LED flash enabled): Allowed
Lock config ACL (LED brightness): Disallowed
Lock config ACL (Timezone offset): Disallowed
Lock config ACL (DST mode): Disallowed
Lock config ACL (Fob Action 1): Disallowed
Lock config ACL (Fob Action 2): Disallowed
Lock config ACL (Fob Action 3): Disallowed
Lock config ACL (Single Lock): Allowed
Lock config ACL (Advertising Mode): Disallowed
Lock config ACL (Timezone ID): Disallowed
Lock config ACL (Unlocked Position Offset Degrees): Disallowed
Lock config ACL (Locked Position Offset Degrees): Disallowed
Lock config ACL (Single Locked Position Offset Degrees): Disallowed
Lock config ACL (Unlocked To Locked Transition Offset Degrees): Disallowed
Lock config ACL (Lock n Go timeout): Disallowed
Lock config ACL (Single button press action): Disallowed
Lock config ACL (Double button press action): Disallowed
Lock config ACL (Detached cylinder): Disallowed
Lock config ACL (Battery type): Disallowed
Lock config ACL (Automatic battery type detection): Disallowed
Lock config ACL (Unlatch duration): Disallowed
Lock config ACL (Auto lock timeout): Disallowed
Lock config ACL (Auto unlock disabled): Allowed
Lock config ACL (Nightmode enabled): Disallowed
Lock config ACL (Nightmode start time): Disallowed
Lock config ACL (Nightmode end time): Disallowed
Lock config ACL (Nightmode auto lock enabled): Disallowed
Lock config ACL (Nightmode auto unlock disabled): Disallowed
Lock config ACL (Nightmode immediate lock on start): Disallowed
Lock config ACL (Auto lock enabled): Allowed
Lock config ACL (Immediate auto lock enabled): Disallowed
Lock config ACL (Auto update enabled): Disallowed
Opener firmware version: 1.10.1
Opener hardware version: 4.17
Opener paired: Yes
Opener valid PIN set: Yes
Opener has keypad: Yes
Opener ACL (Activate Ring-to-Open): Allowed
Opener ACL (Deactivate Ring-to-Open): Allowed
Opener ACL (Electric Strike Actuation): Allowed
Opener ACL (Activate Continuous Mode): Allowed
Opener ACL (Deactivate Continuous Mode): Allowed
Opener ACL (Fob Action 1): Allowed
Opener ACL (Fob Action 2): Allowed
Opener ACL (Fob Action 3): Allowed
Opener config ACL (Name): Disallowed
Opener config ACL (Latitude): Disallowed
Opener config ACL (Longitude): Disallowed
Opener config ACL (Pairing enabled): Disallowed
Opener config ACL (Button enabled): Allowed
Opener config ACL (LED flash enabled): Allowed
Opener config ACL (Timezone offset): Disallowed
Opener config ACL (DST mode): Disallowed
Opener config ACL (Fob Action 1): Disallowed
Opener config ACL (Fob Action 2): Disallowed
Opener config ACL (Fob Action 3): Disallowed
Opener config ACL (Operating Mode): Disallowed
Opener config ACL (Advertising Mode): Disallowed
Opener config ACL (Timezone ID): Disallowed
Opener config ACL (Intercom ID): Disallowed
Opener config ACL (BUS mode Switch): Disallowed
Opener config ACL (Short Circuit Duration): Disallowed
Opener config ACL (Eletric Strike Delay): Disallowed
Opener config ACL (Random Electric Strike Delay): Disallowed
Opener config ACL (Electric Strike Duration): Disallowed
Opener config ACL (Disable RTO after ring): Disallowed
Opener config ACL (RTO timeout): Disallowed
Opener config ACL (Doorbell suppression): Disallowed
Opener config ACL (Doorbell suppression duration): Disallowed
Opener config ACL (Sound Ring): Disallowed
Opener config ACL (Sound Open): Disallowed
Opener config ACL (Sound RTO): Disallowed
Opener config ACL (Sound CM): Disallowed
Opener config ACL (Sound confirmation): Disallowed
Opener config ACL (Sound level): Allowed
Opener config ACL (Single button press action): Disallowed
Opener config ACL (Double button press action): Disallowed
Opener config ACL (Battery type): Disallowed
Opener config ACL (Automatic battery type detection): Disallowed
Network device: GL-S10
Uptime: 346 minutes
Heap: 60980
Stack watermarks: nw: 7396, nuki: 4816
Restart reason FW: RequestedViaMqtt
Restart reason ESP: ESP_RST_SW: Software reset via esp_restart.
```

### TO REPRODUCE
Clean retained MQTT messages and update/restart NH.

### EXPECTED BEHAVIOUR
The entities should exist.

### SCREENSHOTS
N/A

### ADDITIONAL CONTEXT
N/A

**(Please, remember to close the issue when the problem has been addressed)**

### PR DESCRIPTION
**Pull request by iranl**
## Description:

Fix BLE issues where Nuki Hub or Nuki device can get stuck.
Seems related to BLE connections between Nuki Hub and Nuki device not being closed correctly.

This PR aims to fix these issues.
Connecting also seems quicker in initial testing and Nuki Hub is more stable on the ESP32-C6 and now supports pairing

Possibly fixes #432
Fixes #438 
Fixes #326 

~~Needs https://github.com/I-Connect/NukiBleEsp32/pull/71 to be merged first~~
~~Needs https://github.com/I-Connect/NukiBleEsp32/pull/72 to be merged first~~
~~Needs https://github.com/I-Connect/NukiBleEsp32/pull/73 to be merged first~~
~~Needs https://github.com/I-Connect/NukiBleEsp32/pull/74 to be merged first~~

## Checklist:
  - [x] The pull request is done against the latest master branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works
  - [x] I accept the [CLA](https://github.com/technyon/nuki_hub/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by iranl** [comment]
Might still have an issue with updating Nuki device config.

**Comment by technyon** [comment]
Hi,

Why are we shifting the nuki task to core 0? This could lead to race conditions between the nuki and network task.

**Comment by iranl** [comment]
It is advised to run the BLE controller and tasks using BLE (esp-nimble-cpp/nuki_ble) on the same core.

Can't think of what (new) race conditions would/could unsue or in what situations this would cause an issue.
Any call to `delay()` will yield to other tasks, so that already allows both tasks to run pretty much concurrently in the current situation if I am not mistaken.

Have been running this build on multiple ESP devices without issue for a couple of days.

**Comment by technyon** [comment]
I think there are some variables that could be accessed simultaneously from both tasks if running on different cores, this would require some kind of locking. But I'd need to go through the code in detail. Well, let's test it for now it's easy to revert.

**Pull request merged**
