### PR TITLE
Remove Solo1 support + validate HTTPS certs on HTTPS requests

### PR DESCRIPTION
**Pull request by iranl**
## Description:

Validate HTTPS certificate on requests to the update/OTA manifest.

Requires recent HTTPClient and (slightly modified) NetworkClientSecure which does not support Arduino Core 2, thus requires dropping Core 2 and Solo1 support.
Dropping Solo1 support was already planned regardless.

## Checklist:
  - [x] The pull request is done against the latest master branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works
  - [x] I accept the [CLA](https://github.com/technyon/nuki_hub/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by Jason2866** [comment]
@iranl @technyon Not my party ;-) But this 
```
The ESP32-Solo1 is not supported by ESP-IDF 5.1 and as such can't be build using Arduino Core 3 and ESP-IDF 5.1. Release 9.0 was the last (untested) release for the Solo1 which for the Solo1 is built against Arduino Core 2.0.14 and ESP-IDF 4.4.
```
is just wrong!

**Comment by iranl** [comment]
@Jason2866 We are building Arduino as an ESP-IDF component since 9.0. 

If I am correct Arduino as an ESP-IDF component is not supported on Solo1 (but please correct me if I am wrong) in PlatformIO (`framework = arduino, espidf`)
Language in the Readme maybe could be a little clearer on this.

Anyway: Thanks for your work on Tasmota and especially PlatformIO/Arduino/ESP-IDF

**Comment by Jason2866** [comment]
@iranl Supporting the solo1 with IDF is very easy. Only the entry `CONFIG_FREERTOS_UNICORE=y` in sdkconfig is needed to build a firmware for the solo1

**Comment by iranl** [comment]
@Jason2866: Usage of `CONFIG_FREERTOS_UNICORE=y` was not the issue,.

The issue was that `espidf` framework is not defined in https://github.com/tasmota/platform-espressif32/blob/Arduino/IDF5/boards/esp32-solo1.json which causes solo1 build to fail when using `framework = arduino, espidf`

I have switched us over to your pioarduino platform in #452 which does allow espidf framework in https://github.com/pioarduino/platform-espressif32/blob/develop/boards/esp32-solo1.json and added back Solo1 support.

Thanks for the assist and pointing us to your pioarduino fork.

**Pull request merged**
