### PR TITLE
web: improve style for mobile view

### PR DESCRIPTION
**Pull request by duhow**
Make the website more mobile-friendly - note the main menu needs another change (not to do on this PR).

## Changes

* ❗  In cb09e969ac5d9d698d79b930508bc7042d93d199 , the unused code style from original CSS style is removed.
* Added `.adapt` class to `<form>` , this way we skip the page **Access Level Configuration**, which currently has an acceptable view layout for phone.
* 🆕  Inputs are set to `display: block`, underneath the previous cell.
* In fa61c0c7f7e153cb187adb5346c8dea679e3d340 , update `ConfirmationHtml` function to use `HeaderHtml` function, this way, when the user updates configuration, it will use `style` CSS, and the page won't render as a blank website.

**NOTE:** While I separated the content into a new file `style.css`, bear in mind this is not integrated into build process.
I am using https://www.freeformatter.com/css-minifier.html to minify the CSS file and copying the content back again to the header file as `const`. You can request to delete the new `style.css` file if you wish.

### CODE REVIEW

**Comment by iranl** [comment]
I don't have a problem with adding the unminified `style.css`, but would not place it in `src`. I would put it somewhere on the top level, maybe add a `resources` dir or something where `how-to-flash.txt` and `boot_app0.bin` could also live.

**Comment by duhow** [comment]
Mmmm.. what about `include` ?

**Comment by iranl** [comment]
`include` has special purpose in platformio, so I wouldn't use it for other purposes

**Comment by duhow** [comment]
@iranl check now? 🙏🏻

**Review by iranl — APPROVED** [review]

**Pull request merged**
