### PR TITLE
Remove old and modified libs, switch to ESPAsyncWebserver, add support for ESP32-H2 and multiple Ethernet modules

### LINKED ISSUE #431: [Feature request] Add support for DM9051NP Ethernet adapter (ETH01-Evo)
### PROBLEM DESCRIPTION
Is there a reason, why ESP32-C3 SoC / DM5051NP are not supported via ethernet connection?

> Note: LAN8720 modules are only supported on the ESP32, not on the ESP32-S3, ESP32-C3 or ESP-C6

In my special case I have a ETH01-Evo DM9051NP WT ESP32C3-S5 board supporting PoE. Is there a way how I could add the support by myself? Is there any hardware restriction?

### REQUESTED INFORMATION

- [x] Read the [Contributing Guide and Policy](https://github.com/technyon/nuki_hub/blob/master/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/technyon/nuki_hub/blob/master/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/technyon/nuki_hub/issues)
- [x] Searched the problem in [discussions](https://github.com/technyon/nuki_hub/discussions)
- [x] Searched the problem in the [docs](https://github.com/technyon/nuki_hub)
- [x] Searched the problem in the [chat](https://discord.gg/9nPq85bP4p)
- [x] Device used (e.g., ESP32-S3): ESP32-C3
- [x] Nuki Hub binary firmware version number used: 8.35
  - [x] Pre-compiled
  - [x] Self-compiled
- [x] Provide the output of http://nukihubIP/info:
```
System Information
Nuki Hub version: 8.35
Nuki Hub build: 9596430697.1135.1 (release)
run: true
confVersion: 835
deviceId: 1950785077
deviceIdOp: 1950785077
nukiId: 
nukidOp: 
mqttbroker: homeassistant.local
mqttport: 1883
mqttuser: ***
mqttpass: ***
mqttlog: true
checkupdates: false
websrvena: false
lockena: true
lockpin: 
mqttpath: nuki-2
openerena: false
openerpin: 
openercont: false
mqttoppath: 
maxkpad: 
opmaxkpad: 
maxtc: 
opmaxtc: 
enabtlprst: false
mqttca: 
mqttcrt: 
mqttkey: 
hassdiscovery: homeassistant
hassConfigUrl: 
buffsize: 
dhcpena: true
ipaddr: 
ipsub: 
ipgtw: 
dnssrv: 
nwhw: 5
nwwififb: false
rssipb: 60
hostname: nukihub-2
nwbestrssi: false
nettmout: -1
restdisc: true
rstbcn: -1
lockStInterval: 1800
tcPerEntry: false
kpPerEntry: false
configInterval: 3600
batInterval: 1800
kpInterval: 1800
kpCntrlEnabled: true
kpInfoEnabled: false
kpPubCode: false
tcCntrlEnabled: false
tcInfoEnabled: false
cnfInfoEnabled: true
regAsApp: false
regOpnAsApp: false
nrRetry: 3
rtryDelay: 100
crdusr: 
crdpass: 
disnonjson: false
pubAuth: false
pubdbg: false
prdtimeout: 60
offHybrid: false
hybridTimer: 600
hybridAct: false
hybridRtry: false
hasmac: false
macb0: 
macb1: 
macb2: 
latest: 
tsksznetw: 
tsksznuki: 
authmaxentry: 
kpmaxentry: 
tcmaxentry: 
MQTT connected: Yes
Lock firmware version: 
Lock hardware version: 
Lock paired: No
Lock valid PIN set: -
Lock has door sensor: No
Lock has keypad: No
Lock ACL (Lock): Allowed
Lock ACL (Unlock): Allowed
Lock ACL (Unlatch): Allowed
Lock ACL (Lock N Go): Allowed
Lock ACL (Lock N Go Unlatch): Allowed
Lock ACL (Full Lock): Allowed
Lock ACL (Fob Action 1): Allowed
Lock ACL (Fob Action 2): Allowed
Lock ACL (Fob Action 3): Allowed
Lock config ACL (Name): Disallowed
Lock config ACL (Latitude): Disallowed
Lock config ACL (Longitude): Disallowed
Lock config ACL (Auto Unlatch): Disallowed
Lock config ACL (Pairing enabled): Allowed
Lock config ACL (Button enabled): Allowed
Lock config ACL (LED flash enabled): Allowed
Lock config ACL (LED brightness): Disallowed
Lock config ACL (Timezone offset): Disallowed
Lock config ACL (DST mode): Disallowed
Lock config ACL (Fob Action 1): Disallowed
Lock config ACL (Fob Action 2): Disallowed
Lock config ACL (Fob Action 3): Disallowed
Lock config ACL (Single Lock): Allowed
Lock config ACL (Advertising Mode): Disallowed
Lock config ACL (Timezone ID): Disallowed
Lock config ACL (Unlocked Position Offset Degrees): Disallowed
Lock config ACL (Locked Position Offset Degrees): Disallowed
Lock config ACL (Single Locked Position Offset Degrees): Disallowed
Lock config ACL (Unlocked To Locked Transition Offset Degrees): Disallowed
Lock config ACL (Lock n Go timeout): Disallowed
Lock config ACL (Single button press action): Disallowed
Lock config ACL (Double button press action): Disallowed
Lock config ACL (Detached cylinder): Disallowed
Lock config ACL (Battery type): Disallowed
Lock config ACL (Automatic battery type detection): Disallowed
Lock config ACL (Unlatch duration): Disallowed
Lock config ACL (Auto lock timeout): Disallowed
Lock config ACL (Auto unlock disabled): Allowed
Lock config ACL (Nightmode enabled): Disallowed
Lock config ACL (Nightmode start time): Disallowed
Lock config ACL (Nightmode end time): Disallowed
Lock config ACL (Nightmode auto lock enabled): Disallowed
Lock config ACL (Nightmode auto unlock disabled): Disallowed
Lock config ACL (Nightmode immediate lock on start): Disallowed
Lock config ACL (Auto lock enabled): Allowed
Lock config ACL (Immediate auto lock enabled): Disallowed
Lock config ACL (Auto update enabled): Disallowed
Network device: Built-in Wi-Fi
BSSID of AP: 54:AF:97:1A:F2:9B
Uptime: 0 minutes
Heap: 102684
Stack watermarks: nw: 10264, nuki: 7524, pd: 10264
Restart reason FW: NetworkDeviceCriticalFailure
Restart reason ESP: ESP_RST_SW: Software reset via esp_restart.
```

### TO REPRODUCE
Use listed device.

### EXPECTED BEHAVIOUR
Support of listed device.

**(Please, remember to close the issue when the problem has been addressed)**

### PR DESCRIPTION
**Pull request by iranl**
## Description:

-Modify WebCfgServer and WifiManager to use AsyncWebserver
-Ethernet changes based on the work by @technyon in branch https://github.com/technyon/nuki_hub/tree/DM9051
-Remove Arduino core Webserver and Ethernet libs

@technyon: Created this as WIP/draft PR to prevent us doing double work on related issues. Your changes for DM9051 and my changes for AsyncWebserver together should create the option to remove the old libs.

Ethernet completely untested ATM, in the process of testing on ESP32, S3, C3 and C6 on WIFI. Need to solder some headers to my devices to test with my W5500 module.

**Related issue (if applicable):** Fixes #431

To-Do:
- [x] Test on different devices over WIFI
- [x] Test on different devices with different Eth modules (should be able to do W5500 myself)

## Checklist:
  - [x] The pull request is done against the latest master branch
  - [x] Only relevant files were touched
  - [x] ~~Only one feature/fix was added per PR and~~ The code change compiles without warnings
  - [x] The code change is tested and works
  - [x] I accept the [CLA](https://github.com/technyon/nuki_hub/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by technyon** [comment]
My branch compiles, but it's not working yet. The ESP crashes with some SPI error.

**Comment by iranl** [comment]
Had the same issue, there was a typo in SPI.begin (was set to ` SPI.begin(_spi_sck, _spi_miso, **_spi_miso);` instead of ` SPI.begin(_spi_sck, _spi_miso, _spi_mosi);`)

I've tested this build on a C3 over a W5500 without problems and MQTT and AsyncWebserver both work over Ethernet, will try a S3 with W5500 next.

Should make it possible to use SSL over the W5500 also

**Comment by iranl** [comment]
@technyon: Can you try this build with a LAN8720 device?

**Comment by technyon** [comment]
Hi, yes LAN8720 still works.

**Comment by technyon** [comment]
P.S.: I tested with an M5Stack Atom Poe with the W5500, works fine too.

**Comment by technyon** [comment]
Maybe we can reuse the GPIO settings page for that? So that you can configure SPI pins?

**Comment by iranl** [comment]
You also need to select the PHY and Addr so it will not just work on the GPIO page.
I am creating a seperate page now that will only be visible when you select "Custom" ethernet device.

**Comment by technyon** [comment]
True, I'm just thinking of avoiding a conflict with the GPIO configuration.

**Comment by technyon** [comment]
Yes. I think ethernet should override GPIO config.

**Comment by iranl** [comment]
GPIO is now disabled based on Ethernet config.

Current version has been tested on ESP32, ESP32-S3, ESP32-C3 and ESP32-C6 with W5500 and Wifi.

Should be ready for review

**Comment by technyon** [comment]
@iranl Can you confirm this is still working with W5500? I don't know why, but I only get "Failed to configure Ethernet using DHCP", even with the binary I flashed last time that worked. It's probably something in my network.

**Comment by technyon** [comment]
Forget it, I flashed the wrong binary. There's one issue though, disabling DHCP seems to be ignored. I'll merge first though, this PR is big enough already.

**Comment by iranl** [comment]
Static IP fix commited to master

**Pull request merged**
